server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect	# 이 부분 주의!
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop