server:
  port: 8080

spring:
  config:
    import: .env.properties
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      sentinel:
        master: mymaster
        nodes: 127.0.0.1:26379


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect	# 이 부분 주의!
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop
  jwt:
    secret: ${JWT_SECRET_KEY}
    token:
      access-expiration-time: 600000
      refresh-expiration-time: 3600000

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}
  from:
    phone: ${COOLSMS_FROM_PHONE}

naver:
  name: ${NAVER_NAME}
  password: ${NAVER_PASSWORD}

sample:
  email: ${SAMPLE_EMAIL}
  member-name: ${SAMPLE_MEMBER_NAME}
  phone: ${SAMPLE_PHONE}