server:
  port: 8080

spring:
  config:
    import: .env.properties
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect	# 이 부분 주의!
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop

naver:
  name: ${NAVER_NAME}
  password: ${NAVER_PASSWORD}

sample:
  email: ${SAMPLE_EMAIL}
  member-name: ${SAMPLE_MEMBER_NAME}
